"""empty message

Revision ID: 16955943b3b0
Revises: 8ea30317cb63
Create Date: 2024-10-25 17:23:39.757885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16955943b3b0'
down_revision = '8ea30317cb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('eyes_color', sa.String(length=50), nullable=True),
    sa.Column('hair_color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.drop_column('idescription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idescription', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    op.drop_table('people')
    # ### end Alembic commands ###
